default:
  tags:
    - docker
    - pes
    - osc
stages:
  - lint
  - test
  - build
  - release

.defaults_template: &defaults_definition
  image: ${MTR_GITLAB_HOST}/osc/gardener/osc-builder:v4.0.0
  tags:
    - docker
    - pes
    - osc
  before_script:
    - mkdir -p ${GOPATH}/src/${CI_SERVER_HOST}/${CI_PROJECT_PATH}.git
    - rm -rf ${GOPATH}/src/${CI_SERVER_HOST}/${CI_PROJECT_PATH}.git
    - mv $CI_PROJECT_DIR ${GOPATH}/src/${CI_SERVER_HOST}/${CI_PROJECT_PATH}.git
    - cd ${GOPATH}/src/${CI_SERVER_HOST}/${CI_PROJECT_PATH}.git

go-lint:
  stage: lint
  image: golangci/golangci-lint:latest
  script:
    - make lint

unit-tests:
  stage: test
  script:
    - make test

build:
  stage: build
  artifacts:
    expire_in: 5 hrs
    paths:
      - ./bin
  script:
    - make build

build-dev:
  <<: *defaults_definition
  stage: release
  script:
    - hack/container-build.sh osc/upstream/ironcore-dev dev
  only:
    - osc/main

build-branches:
  <<: *defaults_definition
  stage: release
  script:
    - chmod +x hack/container-build.sh
    - hack/container-build.sh osc/upstream/ironcore-dev ${CI_COMMIT_REF_NAME}
  only:
    - /feature-.*$/
    - /bugfix-.*$/
    - /release-fix-.*$/
  except:
    - tags

build-tag:
  <<: *defaults_definition
  stage: release
  script:
    - export LDFLAGS="-s -w"
    - hack/container-build.sh osc/upstream/ironcore-dev ${CI_COMMIT_TAG}
  only:
    # must match 0.0.0...
    - /^v(\d+)\.(\d+)\.(\*|\d+).*$/
  except:
    - branches
