default:
  tags:
    - docker
    - pes
    - osc
stages:
  - lint
  - test
  - build
  - release

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'

.docker-login: &docker-login
  - docker login -u="${OSC_LOGIN}" -p="${OSC_PASSWORD}" "${OSC_HOST}"

go-lint:
  stage: lint
  image: golangci/golangci-lint:latest
  script:
    - make lint

unit-tests:
  stage: test
  script:
    - make test

build:
  stage: build
  artifacts:
    expire_in: 5 hrs
    paths:
      - ./bin
  script:
    - make build

release:
  stage: release
  rules:
    - if: $CI_COMMIT_TAG =~ /^v[0-9]+\..*/
  variables:
    IMG: "${OSC_HOST}/osc/upstream/ironcore-dev/fedhcp:${CI_COMMIT_TAG}"
  dependencies:
    - build
  before_script:
    - *docker-login
  script:
    - docker build -t "${IMG}" -f Dockerfile .
    - docker push "${IMG}"
